<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entrar no X</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/index.css">

</head>
<body>
    <?php if(!isset($this->view->login)) $this->view->login = ''; ?>
 <div class="login-container">
    <div class="mb-4">
          <a href="/sair" title="Sair do sistema">
            <img src="/img/logo-twwiter.avif" alt="Logo X" style="width: 40px;">
          </a>
    </div>
    <h1>Entrar no X</h1>

    <button class="btn btn-google w-100 mb-3">
        <img src="https://www.svgrepo.com/show/355037/google.svg" alt="Google" width="20" class="me-2">
        Fazer login com Google
    </button>

    <button class="btn btn-apple w-100 mb-3">
        <img src="/img/Apple_logo.png" alt="Apple" width="20" class="me-2">
        Entrar com Apple
    </button>

    <div class="divider text-muted">ou</div>

    <form action="/autenticar" method="POST">
        <input type="text" class="form-control mb-3" placeholder="Celular, e-mail ou nome de usuário" required name="email">
        <input type="password" class="form-control mb-3" name="senha" placeholder="Senha" required>

        <button type="submit" class="btn btn-entrar w-100">Avançar</button>
        <?php if(($this->view->login) && $this->view->login == 'erro'): ?>
        <div class="row mt-3">
            <div class="col">
                <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
            </div>
        </div>
        
        <?php endif;?>
    </form>

    <div class="forgot">
        <a href="#">Esqueceu sua senha?</a>
    </div>

    <div class="signup">
        Não tem uma conta? <a href="/signup">Inscreva-se</a>
    </div>
</div>

</body>
</html>
