<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Criar sua Conta</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/css/signup.css">
</head>
<body>
  <div class="signup-container">
    <div class="mb-4">
          <a href="/sair" title="Sair do sistema">
            <img src="/img/logo-twwiter.avif" alt="Logo X" style="width: 40px;">
          </a>
    </div>
    <h1>Criar sua Conta</h1>

    <form action="/registrar" method="POST">
      <input type="text" class="form-control mb-3" name="nome" placeholder="Nome" required>
      <input type="email" class="form-control mb-3" name="email" placeholder="E-mail" required>
      <input type="password" class="form-control mb-3" name="senha" placeholder="Senha" required>

      <label class="text-start w-100 mb-1">Data de nascimento</label>
      <p class="text-muted small text-start">
        Isso não será exibido publicamente. Confirme sua própria idade, mesmo se esta conta for de empresa, de um animal de estimação ou outros.
      </p>

      

      <button type="submit" class="btn btn-entrar w-100">Avançar</button>
    </form>
  </div>
</body>
</html>
